/*
* canvas.h -- Declaration of class KImageCanvas.
* Generated by newclass on Thu Oct  9 09:03:54 EST 1997.
*/
#ifndef SSK_CANVAS_H
#define SSK_CANVAS_H

#include<qwidget.h>
#include<qstring.h>
#include<qwmatrix.h>
#include<qscrollview.h>

class QLabel;

/**
* @short KImageCanvas
* @author Sirtaj Singh Kang (taj@kde.org)
* @version $Id$
*/
class KImageCanvas : public QScrollView
{
	Q_OBJECT
public:
	enum Error { OK, BadPath, BadFormat, NoMemory };
	/**
	* KImageCanvas Constructor
	*/
	KImageCanvas( QWidget *parent = 0 );

	/**
	* KImageCanvas Destructor
	*/
	virtual ~KImageCanvas();

	/**
	* Check canvas status. 
	* @return Status code
	* @see ::Error
	*/
	Error status() const;
public:
	/**
	*
	*/
	int load( const char *file, const char *URL=0 );
	/**
	*
	*/
	bool save( const char *URL, const char *format=0 );

	/**
	* Resets the image to as loaded.
	*/
	void reset();

	/**
	* Clears the image to blank.
	*/
	void clear();
	
	/**
	*
	*/
	void transformImage( const QWMatrix& mat );
	/**
	*
	*/
	void tileToDesktop() const;
	/**
	*
	*/
	void maxToDesktop() const;
	/**
	*
	*/
	void maxpectToDesktop() const;

	QImage getImage() const;

	QString url() const;

public slots:
	void setImage( const QImage& );

protected:
	/**
	*
	*/
	void resizeEvent( QResizeEvent * );

	/**
	* Sets the status.
	*/
	void setStatus( Error );

signals:
	/**
	*
	*/
	void imageSizeChanged();

private:
	Error		_status;
	QString		_file;

	QSize		_originalSize;
	QLabel		*_client;

	QPixmap		*_orig;

	/**
	* Returns a pixmap that is to be used for editing.
	*/
	QPixmap *transPixmap();
};

inline void KImageCanvas::setStatus( Error e )
{
	_status = e;
}

inline QString KImageCanvas::url() const
{
	return _file;
}

#endif // SSK_CANVAS_H
