/*
* colour.h -- Declaration of class ColourFilter.
* Generated by newclass on Tue Sep 22 02:26:05 EST 1998.
*/
#ifndef SSK_COLOUR_H
#define SSK_COLOUR_H

#include"filter.h"

class BriteFilter : public KImageFilter
{

public:
	/**
	* BriteFilter Constructor
	*/
	BriteFilter() : KImageFilter() {}

	/**
	* BriteFilter Destructor
	*/
	virtual ~BriteFilter() {}

	virtual void invoke( QImage before );
        virtual const char *name() const;

	virtual KImageFilter *clone() const;
	
};



class DarkFilter : public KImageFilter
{

public:
	/**
	* DarkFilter Constructor
	*/
	DarkFilter() : KImageFilter() {}

	/**
	* DarkFilter Destructor
	*/
	virtual ~DarkFilter() {}

	virtual void invoke( QImage before );
        virtual const char *name() const;

	virtual KImageFilter *clone() const;
	
};


class GreyFilter : public KImageFilter
{

public:
	/**
	* GreyFilter Constructor
	*/
	GreyFilter() : KImageFilter() {}

	/**
	* GreyFilter Destructor
	*/
	virtual ~GreyFilter() {}

	virtual void invoke( QImage before );
        virtual const char *name() const;

	virtual KImageFilter *clone() const;
	
};

class SmoothFilter : public KImageFilter
{

public:
	/**
	* SmoothFilter Constructor
	*/
	SmoothFilter() : KImageFilter() {}

	/**
	* SmoothFilter Destructor
	*/
	virtual ~SmoothFilter() {}

	virtual void invoke( QImage before );
        virtual const char *name() const;

	virtual KImageFilter *clone() const;
	
};
#endif // SSK_COLOUR_H
